### ISSUE TITLE
No instructions, addon not showing.

### ISSUE THREAD

**Issue by JasonDayspring** [superstyro/AzerothAdmin#8]
This is the only place I could find mention of AzerothAdmin, so I guess this is where I will put this...  There are no instructions on how to bring up the UI, and it's not even showing in my addon list with the rest, so I'm pretty sure it isn't installed correctly, but I can't even guess at what files from /AzerothAdmin-master go in the admin folder, or what to do with the rest.

Is this not ready for public use yet?  Looks awesome from the screenshots.  Wish I knew how to make it work.

**Comment by superstyro** [comment]
My apologies.

You should be able to get the add-on to load by changing the addon folder name to just Azerothadmin by removing -master.

I will make a better release tonight that already has this change made so it is easier to install and run.

There should be a side bar that shows up on the right side of the screen when the addon loads properly and yes it is not production ready as there has been a lot of changes to AzerothCore since I ported AzerothAdmon from TrinityAdmin.

Feel free to add bug reports when you get the add-on to load and test it out. 

I would not recommend using this addon for a 'production server' management in the current state.
